name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Esta condici√≥n es importante para evitar ejecuciones en PRs de forks
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REVOID_TOKEN }}
          persist-credentials: true
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Setup semantic-release
        run: npm ci
      
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.REVOID_USER }}"
          git config --global user.email "${{ secrets.REVOID_USER }}@users.noreply.github.com"
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REVOID_TOKEN }}
          NPM_TOKEN: "dummy"  # Si no usas NPM, esto evita advertencias
        run: npm exec semantic-release
